import nodeResolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import json from "rollup-plugin-json";
import babel from "rollup-plugin-babel";

import packagejson from "./package.json";

export default {
    input: "src/cli.js",
    external: [
        ...Object.keys(packagejson.dependencies),
        "path", "fs", "chalk", "os",
    ],
    output: {
        file: "bundle.js",
        format: "cjs",
        globals: {
            "request-promise": "rp",
        },
        banner: "#!/usr/bin/env node\n/* Generated by rollup. Written by John Schmidt */",
        name: "RallyTools",
        sourcemap: true,
    },
    plugins: [
        nodeResolve({
            preferBuiltins: true,
            module: true,
            //jsnext: true,
        }),
        commonjs({
            include: "node_modules/**",
            extensions: [".js"],
        }),
        json(),
        babel({
            presets: [
                ["@babel/env", {
                    "targets": {
                        "node": "10.0.0",
                    },
                    "modules": false,
                }]
            ],
            plugins: [
                ["@babel/proposal-decorators", {legacy: true}],
                "@babel/proposal-optional-chaining",
            ],
        }),
    ],
}
